import json
import os
from datetime import datetime, timezone
from pathlib import Path

from dotenv import load_dotenv

from audit_log.db import DEFAULT_DB_PATH, init_db
from audit_log.providers import call_provider
from audit_log.risk_classifier import classify

load_dotenv()

DEFAULT_PROVIDER = os.environ.get("AUDIT_LOG_PROVIDER", "ollama")

AUDIT_LOG_MD_PATH = DEFAULT_DB_PATH.parent / "audit-log.md"

_MD_HEADER = (
    "# AI Decision Audit Log\n\n"
    f"Human-readable mirror of `{DEFAULT_DB_PATH.name}`. "
    "Generated by the audit log wrapper -- do not hand-edit.\n"
)


def _now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _append_markdown(row: dict) -> None:
    is_new = not AUDIT_LOG_MD_PATH.exists()

    with AUDIT_LOG_MD_PATH.open("a", encoding="utf-8") as f:
        if is_new:
            f.write(_MD_HEADER)

        f.write(f"\n## Interaction {row['id']} — {row['ts_start']}\n\n")
        f.write(f"- **Provider/model:** {row['provider']} / {row['model']}\n")
        matched_terms = json.loads(row["matched_terms"]) if row["matched_terms"] else []
        f.write(f"- **Risk level:** {row['risk_level']} ({', '.join(matched_terms)})\n")
        f.write(f"- **Stop reason:** {row['stop_reason']}\n")
        f.write(
            f"- **Tokens:** {row['input_tokens']} in / {row['output_tokens']} out\n"
        )
        tool_calls = json.loads(row["tool_calls_json"]) if row["tool_calls_json"] else None
        f.write(f"- **Tool calls:** {tool_calls if tool_calls else 'none'}\n\n")
        f.write("**Prompt:**\n\n")
        for line in row["prompt"].splitlines() or [""]:
            f.write(f"> {line}\n")
        f.write("\n**Response:**\n\n")
        for line in row["response_text"].splitlines() or [""]:
            f.write(f"> {line}\n")
        f.write("\n")


def log_interaction(prompt: str, provider: str | None = None) -> dict:
    provider = provider or DEFAULT_PROVIDER

    ts_start = _now_iso()
    result = call_provider(provider, prompt)
    ts_end = _now_iso()

    risk_level, matched_terms = classify(prompt, result.response_text)

    conn = init_db()
    cursor = conn.execute(
        """
        INSERT INTO interactions (
            ts_start, ts_end, provider, model, prompt, response_text,
            stop_reason, tool_calls_json, input_tokens, output_tokens,
            risk_level, matched_terms
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            ts_start,
            ts_end,
            provider,
            result.model,
            prompt,
            result.response_text,
            result.stop_reason,
            json.dumps(result.tool_calls) if result.tool_calls else None,
            result.input_tokens,
            result.output_tokens,
            risk_level,
            json.dumps(matched_terms) if matched_terms else None,
        ),
    )
    conn.commit()
    interaction_id = cursor.lastrowid

    row = dict(
        id=interaction_id,
        ts_start=ts_start,
        ts_end=ts_end,
        provider=provider,
        model=result.model,
        prompt=prompt,
        response_text=result.response_text,
        stop_reason=result.stop_reason,
        tool_calls_json=json.dumps(result.tool_calls) if result.tool_calls else None,
        input_tokens=result.input_tokens,
        output_tokens=result.output_tokens,
        risk_level=risk_level,
        matched_terms=json.dumps(matched_terms) if matched_terms else None,
    )
    conn.close()

    _append_markdown(row)

    return row
